import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased`}>
                <main className="max-w-6xl mx-auto px-5">
                    <nav>
                        <Navbar />
                    </nav>
                    {children}
                    <footer>
                        <Footer />
                    </footer>
                </main>
            </body>
        </html>
    );
}
