import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { icons } from "lucide-react";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
    title: "CreativeInk",
    description: "Generated by create next app",
    icons:{
        icon:"/icons/logo.png"
    }
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased`}>
                <main className="max-w-6xl mx-auto px-5">
                    <nav>
                        <Navbar />
                    </nav>
                    <div className="min-h-[80vh]">{children}</div>
                    <footer>
                        <Footer />
                    </footer>
                </main>
            </body>
        </html>
    );
}
